---
- hosts: all
  become: true
  vars:
    username: k
    # nvidia-driver-version: 525
  
  tasks:

# Sudo Setup
    - name: Allow 'sudo' group to have passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

# User + Key Setup
    - name: Create a new regular user with sudo privileges
      user:
        name: "{{ username }}"
        state: present
        groups: sudo
        append: true
        create_home: true
        shell: /bin/bash

    - name: Set authorized key for remote user
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

    - name: Disable password authentication for root, SSH only.
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'

# Install Packages
    - name: Update apt
      apt:
        upgrade: true
        update_cache: true

    - name: Install required system packages
      apt:
        name:
          - curl
          - wget
          - net-tools
          - avahi-daemon
          - ca-certificates
          - gnupg
          - git
          - dtach
        state: latest

# Install Nvidia Driver [Optional]
    # Uncomment and update to desired version to install
    # nvidia-driver.
    # - name: Install Nvidia Driver
    #   apt:
    #     name: "nvidia-driver-{{ nvidia-driver-version }}"
    #     state: latest

# Install Docker
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo:
          deb [arch={{ ansible_architecture }}]
          https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }}
          stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest
        update_cache: true

    - name: Make sure we have a 'docker' group
      group:
        name: docker
        state: present

    - name: Add user to 'docker' group
      user:
        name: "{{ username }}"
        groups: docker
        append: true
